### ISSUE TITLE
HowTo for Production Use

### ISSUE THREAD

**Issue by mourningsun75** [bwaldvogel/openmoves#30]
Want to use openmoves in "Production Mode"....
1. Question: How to Change the IP to 0.0.0.0 ?
2. Question: Is there a mini Tutorial how to Use openmoves with openmoves.wsgi and Apache?

**Comment by bwaldvogel** [comment]
1. Do you intend to run the python script on a public IP? I wouldn’t suggest that for production. See question 2.

2. I’m going to update the README to elaborate a bit more on getting openmoves run in production. It would help if you let us know which points are most important/most unclear to you.
Did you successfully test the software locally and did you switch to Postgres already? Those would be prerequisites before going to production.

**Comment by mourningsun75** [comment]
1. no, i just want to test openmoves on my server
2. i dont know how use the wsgi file. the postgres db will be no problem.

**Comment by bwaldvogel** [comment]
I’ve added an Apache example configuration to the README.
